//
//  Country.swift
//  MoneyTracker
//
//  Created by Olha Bereziuk on 25.03.24.
//

import Foundation

enum Country: String, CaseIterable, Identifiable {
    ///Europe
    case austria = "Austria"
    case belgium = "Belgium"
    case estonia = "Estonia"
    case finland = "Finland"
    case france = "France"
    case germany = "Germany"
    case greece = "Greece"
    case ireland = "Ireland"
    case italy = "Italy"
    case latvia = "Latvia"
    case lithuania = "Lithuania"
    case luxembourg = "Luxembourg"
    case malta = "Malta"
    case netherlands = "Netherlands"
    case portugal = "Portugal"
    case slovakia = "Slovakia"
    case slovenia = "Slovenia"
    case spain = "Spain"
    case albania = "Albania"
    case bosniaHerzegovina = "Bosnia and Herzegovina"
    case bulgaria = "Bulgaria"
    case croatia = "Croatia"
    case czechia = "Czech Republic"
    case denmark = "Denmark"
    case georgia = "Georgia"
    case greenland = "Greenland"
    case hungary = "Hungary"
    case iceland = "Iceland"
    case liechtenstein = "Liechtenstein"
    case moldova = "Moldova"
    case northMacedonia = "North Macedonia"
    case norway = "Norway"
    case poland = "Poland"
    case romania = "Romania"
    case serbia = "Serbia"
    case sweden = "Sweden"
    case switzerland = "Switzerland"
    case turkey = "Turkey"
    case ukraine = "Ukraine"
    case unitedKingdom = "United Kingdom"
    ///America
    case usa = "USA"
    case oecsCountries = "OECS countries"
    case aruba = "Aruba"
    case argentina = "Argentina"
    case bahamas = "The Bahamas"
    case barbados = "Barbados"
    case bermuda = "Bermuda"
    case belize = "Belize"
    case bolivia = "Bolivia"
    case brazil = "Brazil"
    case canada = "Canada"
    case caymanIslands = "Cayman Islands"
    case chile = "Chile"
    case colombia = "Colombia"
    case costaRica = "Costa Rica"
    case cuba = "Cuba"
    case curacao = "Curaçao"
    case dominicanRepublic = "Dominican Republic"
    case falklandIslands = "Falkland Islands"
    case guatemala = "Guatemala"
    case guyana = "Guyana"
    case haiti = "Haiti"
    case honduras = "Honduras"
    case jamaica = "Jamaica"
    case mexico = "Mexico"
    case nicaragua = "Nicaragua"
    case panama = "Panama"
    case paraguay = "Paraguay"
    case peru = "Peru"
    case sintMaarten = "Sint Maarten"
    case suriname = "Suriname"
    case trinidadTobago = "Trinidad and Tobago"
    case uruguay = "Uruguay"
    case venezuela = "Venezuela"
    ///Middle East
    case armenia = "Armenia"
    case azerbaijan = "Azerbaijan"
    case bahrain = "Bahrain"
    case cyprus = "Cyprus"
    case israel = "Israel"
    case jordan = "Jordan"
    case kuwait = "Kuwait"
    case lebanon = "Lebanon"
    case uae = "UAE"
    case oman = "Oman"
    case qatar = "Qatar"
    case saudiArabia = "Saudi Arabia"
    case yemen = "Yemen"
    /// Africa
    case westAfrica = "West Africa"
    case centralAfrica = "Central Africa"
    case algeria = "Algeria"
    case angola = "Angola"
    case botswana = "Botswana"
    case burundi = "Burundi"
    case caboVerde = "Cabo Verde"
    case comoros = "Comoros"
    case congo = "Democratic Republic of the Congo"
    case djibouti = "Djibouti"
    case egypt = "Egypt"
    case eritrea = "Eritrea"
    case ethiopia = "Ethiopia"
    case eswatini = "Eswatini"
    case gambia = "Gambia"
    case ghana = "Ghana"
    case guinea = "Guinea"
    case kenya = "Kenya"
    case lesotho = "Lesotho"
    case liberia = "Liberia"
    case libya = "Libya"
    case madagascar = "Madagascar"
    case malawi = "Malawi"
    case mauritius = "Mauritius"
    case mauritania = "Mauritania"
    case morocco = "Morocco"
    case mozambique = "Mozambique"
    case namibia = "Namibia"
    case nigeria = "Nigeria"
    case rwanda = "Rwanda"
    case saoTomeAndPrincipe = "Sao Tome and Principe"
    case seychelles = "Seychelles"
    case sierraLeone = "Sierra Leone"
    case somalia = "Somalia"
    case southAfrica = "South Africa"
    case southSudan = "South Sudan"
    case sudan = "Sudan"
    case tanzania = "Tanzania"
    case tunisia = "Tunisia"
    case uganda = "Uganda"
    case zimbabwe = "Zimbabwe"
    ///Asia & The Pacific region
    case australia = "Australia"
    
    var id: String {
        self.rawValue
    }
}

// MARK: - Extension
extension Country: PickerItem {}
