//
//  Currency.swift
//  MoneyTracker
//
//  Created by Olha Bereziuk on 12.11.24.
//

import Foundation

enum Currency: String, CaseIterable, Identifiable {

    case eur = "EUR"
    case all = "ALL" //Albanian lek
    case bam = "BAM"
    case bgn = "BGN"
    case czk = "CZK"
    case dkk = "DKK"
    case gel = "GEL"
    case huf = "HUF"
    case isk = "ISK"
    case chf = "CHF"
    case mdl = "MDL"
    case mkd = "MKD"
    case nok = "NOK"
    case pln = "PLN"
    case ron = "RON"
    case rsd = "RSD"
    case sek = "SEK"
    case turkey = "TRY"
    case uah = "UAH"
    case gbp = "GBP"
    case usd = "USD"
    case xcd = "XCD"
    case awg = "AWG"
    case ars = "ARS"
    case bsd = "BSD"
    case bbd = "BBD"
    case bmd = "BMD"
    case bzd = "BZD"
    case bob = "BOB"
    case brl = "BRL"
    case cad = "CAD"
    case kyd = "KYD"
    case clp = "CLP"
    case cop = "COP"
    case crc = "CRC"
    case cup = "CUP"
    case ang = "ANG"
    case dop = "DOP"
    case fkp = "FKP"
    case gtq = "GTQ"
    case gyd = "GYD"
    case htg = "HTG"
    case hnl = "HNL"
    case jmd = "JMD"
    case mxn = "MXN"
    case nio = "NIO"
    case pab = "PAB"
    case pyg = "PYG"
    case pen = "PEN"
    case srd = "SRD"
    case ttd = "TTD"
    case uyu = "UYU"
    case ved = "VED"
    case amd = "AMD"
    case azn = "AZN"
    case bhd = "BHD"
    case iqd = "IQD"
    case ils = "ILS"
    case jod = "JOD"
    case kwd = "KWD"
    case lbp = "LBP"
    case syp = "SYP"
    case aed = "AED"
    case omr = "OMR"
    case qar = "QAR"
    case sar = "SAR"
    case yer = "YER"
    case xaf = "XAF"
    case xof = "XOF"
    case dzd = "DZD"
    case aoa = "AOA"
    case bwp = "BWP"
    case bif = "BIF"
    case cve = "CVE"
    case kmf = "KMF"
    case cdf = "CDF"
    case djf = "DJF"
    case egp = "EGP"
    case ern = "ERN"
    case etb = "ETB"
    case szl = "SZL"
    case gmd = "GMD"
    case ghs = "GHS"
    case gnf = "GNF"
    case kes = "KES"
    case lsl = "LSL"
    case lrd = "LRD"
    case lyd = "LYD"
    case mga = "MGA"
    case mwk = "MWK"
    case mur = "MUR"
    case mru = "MRU"
    case mad = "MAD"
    case mzn = "MZN"
    case nad = "NAD"
    case ngn = "NGN"
    case rwf = "RWF"
    case stn = "STN"
    case scr = "SCR"
    case sll = "SLL"
    case sos = "SOS"
    case zar = "ZAR"
    case ssp = "SSP"
    case sdg = "SDG"
    case tzs = "TZS"
    case tnd = "TND"
    case ugx = "UGX"
    case aud = "AUD"
    
    var id: String {
        self.rawValue
    }
}

// MARK: - Extension
extension Currency: PickerItem {}
